spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Boot
    username: postgres
    password: Dima4532

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update